main: me.cheezburga.skcheez.SkCheez
name: SkCheez
version: '${project.version}'
description: "A Skript addon which adds useful features to your server."
api-version: '1.17'
author: cheezburga
website: https://github.com/cheeezburga/SkCheez/
depend:
  - Skript
commands:
    skcheez:
        description: Main SkCheez command
        permission: skcheez.command
permissions:
    skcheez.command:
        default: op
        description: Permission to use SkCheez's main command